### PR TITLE
Fix to allow bows to be repaired by blacksmith

### PR DESCRIPTION
**Pull request by twa16**
Allows Bows to be fixed

### CODE REVIEW

**Comment by ghost** [comment]
Can you please elaborate? What's so special about the bow as a tool?

**Comment by twa16** [comment]
As you use the bow its durability drops. Many people on my server complain because they cannot repair their enchanted bows. The bows are the most used weapon on my server so I was hoping I could get a way of fixing them. I know there are other servers out there with the same issue so I sent the request to at least bring attention to issue if not fix it.

**Comment by ghost** [comment]
Sure there is. Set damage to zero and take away iconomy money.

**Comment by twa16** [comment]
But that is not coded in so this is a simple fix.

**Comment by Sydael** [comment]
Yeah, i would really appreciate that.

**Pull request merged**
