### PR TITLE
Add Spout support to traders

### PR DESCRIPTION
**Pull request by ericpauley**
Currently, traders have item duplication issues. This pull will eliminate those issues for servers running spout. Servers without spout will have a warning message displayed and will carry on happily using the same method as before.

### CODE REVIEW

**Comment by ghost** [comment]
<insert facepalm picture here>

I swear does no one read the wiki anymore?

I quote directly off wiki:

"Why won't you add Spout support so traders aren't buggy? 
- Spout is a great API for client-side additions to Bukkit. However, we are not interested in supporting it server-side. We don't want people to feel forced to download Spout if they want to use trader NPCs."

**Comment by ericpauley** [comment]
A couple of things about that comment:
1. Spout is not required to use traders with this pull - they work just like before without spout
2. The 1.x pages are outdated and those intentions are no longer true. In fact, 2.0 citizens is planned to use spout for traders.
3. I have been talking with aPunch about this pull and he already likes it. He's just waiting for Fullwall to approve it. The pull request is mainly a formality.

Again, I can't stress enough that spout is not required to use citizens with this pull. People not using spout won't notice a difference other than the startup warning stating that traders are susceptible to the item duplication bug.

**Comment by Fureniku** [comment]
What exactly is the bug you're talking about by the way?

**Comment by ericpauley** [comment]
It's possible to dupe items from traders by making extremely fast movements of items/ closing the trader after dropping items, etc.

**Pull request merged**
